apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: console-deployment
spec:
  selector:
    matchLabels:
      app: console
  replicas: 1
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: #Alterar Imagem
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080