apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: iot-deployment
spec:
  selector:
    matchLabels:
      app: iot
  replicas: 1
  template:
    metadata:
      labels:
        app: iot
    spec:
      containers:
      - name: iot
        image: mateuscg/iot:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080